name: run tests with maven - first try
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      h2:
        image: "docker://oaknd1/h2-docker:latest"
        options: --name=h2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn -B clean install
      - name: Run tests
        env:
          SPRING_DATASOURCE_URL: jdbc:h2:mem:db
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
        run: mvn test

