name: Build with Maven
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
    # https://hub.docker.com/_/mysql
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          #MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 3306:3306
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # https://github.com/actions/cache/blob/main/examples.md#java---maven
      - name: Cache local Maven repo
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Build with Maven
        run: mvn clean install
